--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: python-example
  name: python-example
spec: 
  minReadySeconds: 5
  replicas: 1
  selector: 
    matchLabels: 
      app: python-example
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      labels: 
        app: python-example
    spec: 
      containers: 
        - 
          image: python-example
          name: python-example
          ports: 
            - 
              containerPort: 80
          resources: 
            limits: 
              cpu: 100m
            requests: 
              cpu: 100m

